# Generated by Django 4.1.7 on 2023-03-02 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictPersonality', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='id',
        ),
        migrations.AlterField(
            model_name='questions',
            name='qId',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
