# Generated by Django 4.1.7 on 2023-03-02 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictPersonality', '0002_remove_questions_id_alter_questions_qid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
