# Generated by Django 4.1.7 on 2023-03-03 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictPersonality', '0004_alter_questions_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Responses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ext_1', models.IntegerField(choices=[(1, 'Veryinaccurate'), (2, 'Moderatelyinaccurate'), (3, 'Neutral'), (4, 'Moderatelyaccurate'), (5, 'Veryaccurate')])),
                ('ext_2', models.IntegerField(choices=[(1, 'Veryinaccurate'), (2, 'Moderatelyinaccurate'), (3, 'Neutral'), (4, 'Moderatelyaccurate'), (5, 'Veryaccurate')])),
                ('ext_3', models.IntegerField(choices=[(1, 'Veryinaccurate'), (2, 'Moderatelyinaccurate'), (3, 'Neutral'), (4, 'Moderatelyaccurate'), (5, 'Veryaccurate')])),
                ('ext_4', models.IntegerField(choices=[(1, 'Veryinaccurate'), (2, 'Moderatelyinaccurate'), (3, 'Neutral'), (4, 'Moderatelyaccurate'), (5, 'Veryaccurate')])),
                ('ext_5', models.IntegerField(choices=[(1, 'Veryinaccurate'), (2, 'Moderatelyinaccurate'), (3, 'Neutral'), (4, 'Moderatelyaccurate'), (5, 'Veryaccurate')])),
                ('ext_6', models.IntegerField(choices=[(1, 'Veryinaccurate'), (2, 'Moderatelyinaccurate'), (3, 'Neutral'), (4, 'Moderatelyaccurate'), (5, 'Veryaccurate')])),
                ('ext_7', models.IntegerField(choices=[(1, 'Veryinaccurate'), (2, 'Moderatelyinaccurate'), (3, 'Neutral'), (4, 'Moderatelyaccurate'), (5, 'Veryaccurate')])),
                ('ext_8', models.IntegerField(choices=[(1, 'Veryinaccurate'), (2, 'Moderatelyinaccurate'), (3, 'Neutral'), (4, 'Moderatelyaccurate'), (5, 'Veryaccurate')])),
                ('ext_9', models.IntegerField(choices=[(1, 'Veryinaccurate'), (2, 'Moderatelyinaccurate'), (3, 'Neutral'), (4, 'Moderatelyaccurate'), (5, 'Veryaccurate')])),
                ('ext_10', models.IntegerField(choices=[(1, 'Veryinaccurate'), (2, 'Moderatelyinaccurate'), (3, 'Neutral'), (4, 'Moderatelyaccurate'), (5, 'Veryaccurate')])),
                ('nrt_1', models.IntegerField(choices=[(1, 'Veryinaccurate'), (2, 'Moderatelyinaccurate'), (3, 'Neutral'), (4, 'Moderatelyaccurate'), (5, 'Veryaccurate')])),
                ('nrt_2', models.IntegerField(choices=[(1, 'Veryinaccurate'), (2, 'Moderatelyinaccurate'), (3, 'Neutral'), (4, 'Moderatelyaccurate'), (5, 'Veryaccurate')])),
                ('nrt_3', models.IntegerField(choices=[(1, 'Veryinaccurate'), (2, 'Moderatelyinaccurate'), (3, 'Neutral'), (4, 'Moderatelyaccurate'), (5, 'Veryaccurate')])),
                ('nrt_4', models.IntegerField(choices=[(1, 'Veryinaccurate'), (2, 'Moderatelyinaccurate'), (3, 'Neutral'), (4, 'Moderatelyaccurate'), (5, 'Veryaccurate')])),
                ('nrt_5', models.IntegerField(choices=[(1, 'Veryinaccurate'), (2, 'Moderatelyinaccurate'), (3, 'Neutral'), (4, 'Moderatelyaccurate'), (5, 'Veryaccurate')])),
                ('nrt_6', models.IntegerField(choices=[(1, 'Veryinaccurate'), (2, 'Moderatelyinaccurate'), (3, 'Neutral'), (4, 'Moderatelyaccurate'), (5, 'Veryaccurate')])),
                ('nrt_7', models.IntegerField(choices=[(1, 'Veryinaccurate'), (2, 'Moderatelyinaccurate'), (3, 'Neutral'), (4, 'Moderatelyaccurate'), (5, 'Veryaccurate')])),
                ('nrt_8', models.IntegerField(choices=[(1, 'Veryinaccurate'), (2, 'Moderatelyinaccurate'), (3, 'Neutral'), (4, 'Moderatelyaccurate'), (5, 'Veryaccurate')])),
                ('nrt_9', models.IntegerField(choices=[(1, 'Veryinaccurate'), (2, 'Moderatelyinaccurate'), (3, 'Neutral'), (4, 'Moderatelyaccurate'), (5, 'Veryaccurate')])),
                ('nrt_10', models.IntegerField(choices=[(1, 'Veryinaccurate'), (2, 'Moderatelyinaccurate'), (3, 'Neutral'), (4, 'Moderatelyaccurate'), (5, 'Veryaccurate')])),
                ('agr_1', models.IntegerField(choices=[(1, 'Veryinaccurate'), (2, 'Moderatelyinaccurate'), (3, 'Neutral'), (4, 'Moderatelyaccurate'), (5, 'Veryaccurate')])),
                ('agr_2', models.IntegerField(choices=[(1, 'Veryinaccurate'), (2, 'Moderatelyinaccurate'), (3, 'Neutral'), (4, 'Moderatelyaccurate'), (5, 'Veryaccurate')])),
                ('agr_3', models.IntegerField(choices=[(1, 'Veryinaccurate'), (2, 'Moderatelyinaccurate'), (3, 'Neutral'), (4, 'Moderatelyaccurate'), (5, 'Veryaccurate')])),
                ('agr_4', models.IntegerField(choices=[(1, 'Veryinaccurate'), (2, 'Moderatelyinaccurate'), (3, 'Neutral'), (4, 'Moderatelyaccurate'), (5, 'Veryaccurate')])),
                ('agr_5', models.IntegerField(choices=[(1, 'Veryinaccurate'), (2, 'Moderatelyinaccurate'), (3, 'Neutral'), (4, 'Moderatelyaccurate'), (5, 'Veryaccurate')])),
                ('agr_6', models.IntegerField(choices=[(1, 'Veryinaccurate'), (2, 'Moderatelyinaccurate'), (3, 'Neutral'), (4, 'Moderatelyaccurate'), (5, 'Veryaccurate')])),
                ('agr_7', models.IntegerField(choices=[(1, 'Veryinaccurate'), (2, 'Moderatelyinaccurate'), (3, 'Neutral'), (4, 'Moderatelyaccurate'), (5, 'Veryaccurate')])),
                ('agr_8', models.IntegerField(choices=[(1, 'Veryinaccurate'), (2, 'Moderatelyinaccurate'), (3, 'Neutral'), (4, 'Moderatelyaccurate'), (5, 'Veryaccurate')])),
                ('agr_9', models.IntegerField(choices=[(1, 'Veryinaccurate'), (2, 'Moderatelyinaccurate'), (3, 'Neutral'), (4, 'Moderatelyaccurate'), (5, 'Veryaccurate')])),
                ('agr_10', models.IntegerField(choices=[(1, 'Veryinaccurate'), (2, 'Moderatelyinaccurate'), (3, 'Neutral'), (4, 'Moderatelyaccurate'), (5, 'Veryaccurate')])),
                ('csn_1', models.IntegerField(choices=[(1, 'Veryinaccurate'), (2, 'Moderatelyinaccurate'), (3, 'Neutral'), (4, 'Moderatelyaccurate'), (5, 'Veryaccurate')])),
                ('csn_2', models.IntegerField(choices=[(1, 'Veryinaccurate'), (2, 'Moderatelyinaccurate'), (3, 'Neutral'), (4, 'Moderatelyaccurate'), (5, 'Veryaccurate')])),
                ('csn_3', models.IntegerField(choices=[(1, 'Veryinaccurate'), (2, 'Moderatelyinaccurate'), (3, 'Neutral'), (4, 'Moderatelyaccurate'), (5, 'Veryaccurate')])),
                ('csn_4', models.IntegerField(choices=[(1, 'Veryinaccurate'), (2, 'Moderatelyinaccurate'), (3, 'Neutral'), (4, 'Moderatelyaccurate'), (5, 'Veryaccurate')])),
                ('csn_5', models.IntegerField(choices=[(1, 'Veryinaccurate'), (2, 'Moderatelyinaccurate'), (3, 'Neutral'), (4, 'Moderatelyaccurate'), (5, 'Veryaccurate')])),
                ('csn_6', models.IntegerField(choices=[(1, 'Veryinaccurate'), (2, 'Moderatelyinaccurate'), (3, 'Neutral'), (4, 'Moderatelyaccurate'), (5, 'Veryaccurate')])),
                ('csn_7', models.IntegerField(choices=[(1, 'Veryinaccurate'), (2, 'Moderatelyinaccurate'), (3, 'Neutral'), (4, 'Moderatelyaccurate'), (5, 'Veryaccurate')])),
                ('csn_8', models.IntegerField(choices=[(1, 'Veryinaccurate'), (2, 'Moderatelyinaccurate'), (3, 'Neutral'), (4, 'Moderatelyaccurate'), (5, 'Veryaccurate')])),
                ('csn_9', models.IntegerField(choices=[(1, 'Veryinaccurate'), (2, 'Moderatelyinaccurate'), (3, 'Neutral'), (4, 'Moderatelyaccurate'), (5, 'Veryaccurate')])),
                ('csn_10', models.IntegerField(choices=[(1, 'Veryinaccurate'), (2, 'Moderatelyinaccurate'), (3, 'Neutral'), (4, 'Moderatelyaccurate'), (5, 'Veryaccurate')])),
                ('opn_1', models.IntegerField(choices=[(1, 'Veryinaccurate'), (2, 'Moderatelyinaccurate'), (3, 'Neutral'), (4, 'Moderatelyaccurate'), (5, 'Veryaccurate')])),
                ('opn_2', models.IntegerField(choices=[(1, 'Veryinaccurate'), (2, 'Moderatelyinaccurate'), (3, 'Neutral'), (4, 'Moderatelyaccurate'), (5, 'Veryaccurate')])),
                ('opn_3', models.IntegerField(choices=[(1, 'Veryinaccurate'), (2, 'Moderatelyinaccurate'), (3, 'Neutral'), (4, 'Moderatelyaccurate'), (5, 'Veryaccurate')])),
                ('opn_4', models.IntegerField(choices=[(1, 'Veryinaccurate'), (2, 'Moderatelyinaccurate'), (3, 'Neutral'), (4, 'Moderatelyaccurate'), (5, 'Veryaccurate')])),
                ('opn_5', models.IntegerField(choices=[(1, 'Veryinaccurate'), (2, 'Moderatelyinaccurate'), (3, 'Neutral'), (4, 'Moderatelyaccurate'), (5, 'Veryaccurate')])),
                ('opn_6', models.IntegerField(choices=[(1, 'Veryinaccurate'), (2, 'Moderatelyinaccurate'), (3, 'Neutral'), (4, 'Moderatelyaccurate'), (5, 'Veryaccurate')])),
                ('opn_7', models.IntegerField(choices=[(1, 'Veryinaccurate'), (2, 'Moderatelyinaccurate'), (3, 'Neutral'), (4, 'Moderatelyaccurate'), (5, 'Veryaccurate')])),
                ('opn_8', models.IntegerField(choices=[(1, 'Veryinaccurate'), (2, 'Moderatelyinaccurate'), (3, 'Neutral'), (4, 'Moderatelyaccurate'), (5, 'Veryaccurate')])),
                ('opn_9', models.IntegerField(choices=[(1, 'Veryinaccurate'), (2, 'Moderatelyinaccurate'), (3, 'Neutral'), (4, 'Moderatelyaccurate'), (5, 'Veryaccurate')])),
                ('opn_10', models.IntegerField(choices=[(1, 'Veryinaccurate'), (2, 'Moderatelyinaccurate'), (3, 'Neutral'), (4, 'Moderatelyaccurate'), (5, 'Veryaccurate')])),
            ],
        ),
    ]
